<?php

namespace Acme\ChatonDL16Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChatonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatonRepository extends EntityRepository
{
}
